services:
  - type: web
    name: order-management-system
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
    disks:
      - name: data
        mountPath: /app/data # Or the correct path to your data dir
        sizeGB: 1