services:
  - type: web
    name: order-management-system
    env: node
    plan: free
    buildCommand: "npm cache clean --force && npm install --include=dev && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
